# Generated by Django 4.1.3 on 2022-12-05 20:19

from django.db import migrations, models
import django.utils.timezone
import django_cleanhtmlfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blogid",
                    models.UUIDField(
                        default=uuid.UUID("d2fa86b1-2d6c-46b1-9d8c-b6cd623c767d"),
                        editable=False,
                        unique=True,
                    ),
                ),
                ("title", models.TextField(default=None)),
                (
                    "category",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                ("article", django_cleanhtmlfield.fields.HTMLField()),
                ("poted_by", models.CharField(default="Admin", max_length=250)),
                ("likes", models.IntegerField(default=None)),
                ("views", models.IntegerField(default=None)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
