# Generated by Django 4.1.3 on 2022-12-05 20:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="poted_by",
            new_name="posted_by",
        ),
        migrations.AlterField(
            model_name="blog",
            name="blogid",
            field=models.UUIDField(
                default=uuid.UUID("d3e51d8a-76da-4ea2-b0ed-8a6e51cce541"),
                editable=False,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="blog_comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField(default=None)),
                ("commented_by", models.CharField(default=None, max_length=150)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.blog",
                        verbose_name="blog comments",
                    ),
                ),
            ],
        ),
    ]
