# Generated by Django 4.1.3 on 2022-12-05 21:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_rename_poted_by_blog_posted_by_alter_blog_blogid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="blogimage",
            field=models.ImageField(default="blog_default.webp", upload_to="blog"),
        ),
        migrations.AddField(
            model_name="blog",
            name="blogthumbnail",
            field=models.ImageField(
                blank=None, default=None, null=None, upload_to="blog/thumbnail"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="blogid",
            field=models.UUIDField(
                default=uuid.UUID("6e484acd-07de-4938-907b-a9653b04b399"),
                editable=False,
                unique=True,
            ),
        ),
    ]
