# Generated by Django 4.1.3 on 2022-12-05 21:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_blog_blogimage_blog_blogthumbnail_alter_blog_blogid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="blogid",
            field=models.UUIDField(
                default=uuid.UUID("ddfa17e0-cf2d-426e-8d45-6134d92f01d0"),
                editable=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="blogthumbnail",
            field=models.ImageField(
                blank=None,
                default="blog_thumbnail_default.webp",
                null=None,
                upload_to="blog/thumbnail",
            ),
        ),
    ]
