# Generated by Django 4.1.3 on 2022-12-05 21:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_blog_blogid_alter_blog_blogthumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="blogid",
            field=models.UUIDField(
                default=uuid.UUID("e5611e30-c796-4e3c-9cc1-09eb5eda15fb"),
                editable=False,
            ),
        ),
    ]
