# Generated by Django 4.1.3 on 2022-12-05 22:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_blog_blogid"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="blog",
            name="blogid",
            field=models.UUIDField(
                default=uuid.UUID("2f885b0f-e8ab-4955-ad70-8a262b048b84"),
                editable=False,
            ),
        ),
    ]
