# Generated by Django 4.1.3 on 2022-12-05 22:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_blog_blogid_alter_blog_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="blogid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
