# Generated by Django 4.1.3 on 2022-12-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_blog_blogid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog_comment",
            name="commented_by",
        ),
        migrations.AddField(
            model_name="blog_comment",
            name="fullname",
            field=models.CharField(default=None, max_length=300),
        ),
    ]
