# Generated by Django 4.1.3 on 2022-11-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0002_cart_bookslug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="bookslug",
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
