# Generated by Django 4.1.3 on 2022-12-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0005_category_subcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(default=None),
        ),
    ]
