# Generated by Django 4.1.3 on 2022-12-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0007_alter_category_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="tag",
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
