# Generated by Django 4.1.3 on 2022-12-02 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("frontend", "0008_alter_category_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="recent_viewied_item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.CharField(default=None, max_length=150)),
                ("booktitle", models.CharField(default=None, max_length=250)),
                ("bookthumbnail", models.CharField(default=None, max_length=250)),
                ("bookprice", models.DecimalField(decimal_places=2, max_digits=9)),
                ("booktype", models.CharField(default=None, max_length=250)),
                ("bookauthor", models.CharField(default=None, max_length=250)),
                (
                    "bookslug",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="cart",
                    ),
                ),
            ],
        ),
    ]
