# Generated by Django 4.1.3 on 2022-12-03 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0009_recent_viewied_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="recent_viewied_item",
            name="bookquantity",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
