# Generated by Django 4.1.3 on 2022-12-05 18:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0010_recent_viewied_item_bookquantity"),
    ]

    operations = [
        migrations.CreateModel(
            name="faq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quation", models.TextField(default=None)),
                ("answer", models.TextField(default=None)),
                ("created_at", models.TextField(default=django.utils.timezone.now)),
            ],
        ),
    ]
