# Generated by Django 4.1.3 on 2022-12-05 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0011_faq"),
    ]

    operations = [
        migrations.RenameField(
            model_name="faq",
            old_name="quation",
            new_name="question",
        ),
    ]
