# Generated by Django 4.1.3 on 2022-12-07 16:50

from django.db import migrations, models
import django_cleanhtmlfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0012_rename_quation_faq_question"),
    ]

    operations = [
        migrations.CreateModel(
            name="aboutUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", django_cleanhtmlfield.fields.HTMLField()),
                ("our_story", django_cleanhtmlfield.fields.HTMLField()),
                ("our_who", django_cleanhtmlfield.fields.HTMLField()),
                ("our_why", django_cleanhtmlfield.fields.HTMLField()),
                ("our_what", django_cleanhtmlfield.fields.HTMLField()),
                ("our_where", django_cleanhtmlfield.fields.HTMLField()),
                ("our_when", django_cleanhtmlfield.fields.HTMLField()),
                ("our_how", django_cleanhtmlfield.fields.HTMLField()),
                ("our_price", django_cleanhtmlfield.fields.HTMLField()),
                ("our_philosophy", django_cleanhtmlfield.fields.HTMLField()),
                ("our_mantra", django_cleanhtmlfield.fields.HTMLField()),
                ("our_goal", django_cleanhtmlfield.fields.HTMLField()),
                ("who_we_serve", django_cleanhtmlfield.fields.HTMLField()),
            ],
        ),
    ]
