# Generated by Django 4.1.3 on 2022-12-07 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0013_aboutus"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="aboutUs",
            new_name="about_us",
        ),
    ]
