# Generated by Django 4.1.3 on 2023-04-11 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0014_rename_aboutus_about_us"),
    ]

    operations = [
        migrations.CreateModel(
            name="contact_us",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=200)),
                ("email", models.EmailField(default=None, max_length=254)),
                ("subject", models.CharField(default=None, max_length=300)),
                ("message", models.TextField(default=None)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
