# Generated by Django 4.1.3 on 2023-04-13 23:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0015_contact_us"),
    ]

    operations = [
        migrations.CreateModel(
            name="newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(default=None, max_length=254)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023,
                            4,
                            13,
                            23,
                            23,
                            26,
                            271588,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
            ],
        ),
    ]
