# Generated by Django 4.1.3 on 2023-04-13 23:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0016_newsletter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
