# Generated by Django 4.1.3 on 2022-11-24 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentications", "0002_account_last_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="first_name",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="last_name",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
