# Generated by Django 4.1.3 on 2023-05-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentications", "0003_alter_account_first_name_alter_account_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_google_auth",
            field=models.BooleanField(default=True),
        ),
    ]
