# Generated by Django 4.1.3 on 2023-05-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentications", "0004_account_is_google_auth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="email_verify",
            field=models.BooleanField(default=True),
        ),
    ]
