# Generated by Django 4.1.3 on 2022-11-15 19:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(default=None)),
                ("quantity", models.IntegerField(default=None)),
                (
                    "author",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                ("review", models.IntegerField(blank=True, default=None, null=True)),
                ("default_price", models.DecimalField(decimal_places=2, max_digits=9)),
                (
                    "deault_booktype",
                    models.CharField(
                        choices=[
                            ("PAPERBACK", "PAPERBACK"),
                            ("AUDIOBOOK", "AUDIOBOOK"),
                            ("EBOOK", "EBOOK"),
                            ("HARDCOVER", "HARDCOVER"),
                        ],
                        default="PAPERBACK",
                        max_length=250,
                    ),
                ),
                ("thumbnail", models.CharField(default=None, max_length=250)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("product_name", models.CharField(default=None, max_length=250)),
                (
                    "product_type",
                    models.CharField(
                        default=None, max_length=250, verbose_name="retial or wholesale"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="bookimages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thumbnail", models.TextField(blank=True, default=None, null=True)),
                ("images", models.ImageField(upload_to="media")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cpanel.book",
                        verbose_name="book",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="bookdetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booktype", models.CharField(default=None, max_length=150)),
                ("price", models.DecimalField(decimal_places=2, max_digits=9)),
                ("description", models.TextField(default=None)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cpanel.book",
                        verbose_name="book",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cpanel.product",
                verbose_name="product",
            ),
        ),
    ]
