# Generated by Django 4.1.3 on 2023-02-02 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Addresse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.EmailField(default=None, max_length=254)),
                ("user_type", models.CharField(default="guest", max_length=30)),
                ("first_name", models.CharField(default=None, max_length=300)),
                ("last_name", models.CharField(default=None, max_length=300)),
                ("address1", models.CharField(default=None, max_length=300)),
                (
                    "address2",
                    models.CharField(
                        blank=True, default=None, max_length=300, null=True
                    ),
                ),
                ("country", models.CharField(default=None, max_length=250)),
                ("region_or_state", models.CharField(default=None, max_length=250)),
                ("city", models.CharField(default=None, max_length=300)),
                (
                    "phonenumber",
                    models.CharField(
                        blank=True, default=None, max_length=14, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(default=None)),
                ("quantity", models.IntegerField(default=None)),
                (
                    "author",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                ("review", models.IntegerField(blank=True, default=None, null=True)),
                ("slug", models.SlugField(default=None)),
                ("default_price", models.DecimalField(decimal_places=2, max_digits=9)),
                (
                    "default_type",
                    models.CharField(
                        choices=[
                            ("PAPERBACK", "PAPERBACK"),
                            ("AUDIOBOOK", "AUDIOBOOK"),
                            ("EBOOK", "EBOOK"),
                            ("HARDCOVER", "HARDCOVER"),
                        ],
                        default="PAPERBACK",
                        max_length=250,
                    ),
                ),
                ("thumbnail", models.CharField(default=None, max_length=250)),
                ("on_sale", models.BooleanField(default=False)),
                ("sales_discount", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(default=None, max_length=150)),
                (
                    "percentage",
                    models.CharField(
                        default=None, help_text="percentage ex: 20", max_length=100
                    ),
                ),
                ("expires_on", models.DateTimeField(default=None)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="general_settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_title", models.CharField(default=None, max_length=250)),
                (
                    "tage_line",
                    models.CharField(
                        default=None,
                        help_text="In few words, explain what this site is about. ",
                        max_length=250,
                    ),
                ),
                (
                    "default_email",
                    models.EmailField(
                        default=None,
                        help_text="The defaul email on home page.",
                        max_length=254,
                    ),
                ),
                (
                    "default_phone",
                    models.CharField(
                        default=None,
                        help_text="The default number on home page.",
                        max_length=150,
                    ),
                ),
                (
                    "facebook_handle",
                    models.CharField(
                        default=None,
                        help_text="Enter your facebook handle.",
                        max_length=150,
                    ),
                ),
                (
                    "twitter_handle",
                    models.CharField(
                        default=None,
                        help_text="Enter your twitter handle.",
                        max_length=150,
                    ),
                ),
                (
                    "instagram_handle",
                    models.CharField(
                        default=None,
                        help_text="Enter your intagram handle.",
                        max_length=150,
                    ),
                ),
                (
                    "youtube_handle",
                    models.CharField(
                        default=None,
                        help_text="Enter your youtube handle.",
                        max_length=150,
                    ),
                ),
                (
                    "pinterest_handle",
                    models.CharField(
                        default=None,
                        help_text="Enter your pinterest handle.",
                        max_length=150,
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        default=None, help_text="bookshop physical address"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("orderid", models.CharField(default="None", max_length=10)),
                ("email", models.EmailField(default=None, max_length=254)),
                ("status", models.CharField(default="pending", max_length=250)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=None, max_digits=10),
                ),
                ("payment_method", models.CharField(default=None, max_length=250)),
                ("shipping_fee", models.CharField(default=None, max_length=250)),
                (
                    "discount",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cpanel.addresse",
                        verbose_name="shipping address",
                    ),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cpanel.coupon",
                        verbose_name="coupon code",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("product_name", models.CharField(default=None, max_length=250)),
                (
                    "product_type",
                    models.CharField(
                        default=None, max_length=250, verbose_name="retial or wholesale"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="ratings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stars", models.IntegerField(default=0)),
                ("title", models.TextField(default=None)),
                ("comments", models.TextField(blank=True, default=None, null=True)),
                ("likes", models.IntegerField(default=0)),
                ("dislikes", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cpanel.book",
                        verbose_name="book rated",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user rating",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserLikes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("liked", models.BooleanField(default=False)),
                ("disliked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "ratings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cpanel.ratings",
                        verbose_name="user likes",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="order_book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.CharField(default=None, max_length=150)),
                ("booktitle", models.CharField(default=None, max_length=250)),
                ("bookquantity", models.IntegerField(default=None)),
                ("bookthumbnail", models.CharField(default=None, max_length=250)),
                ("bookprice", models.DecimalField(decimal_places=2, max_digits=9)),
                ("booktype", models.CharField(default=None, max_length=250)),
                ("bookauthor", models.CharField(default=None, max_length=250)),
                (
                    "bookslug",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "ordernumber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cpanel.order",
                        verbose_name="cart",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OnSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discount", models.IntegerField(default=0)),
                ("periode", models.DateTimeField(default=None)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cpanel.book",
                        verbose_name="book on sale",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="on sale created by ",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DealofWeek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discount", models.IntegerField(default=0)),
                ("periode", models.DateTimeField(default=None)),
                ("quantity", models.IntegerField(default=0)),
                ("sold", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cpanel.book",
                        verbose_name="deals of the week",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="deals of the week ",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="bookimages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thumbnail", models.TextField(blank=True, default=None, null=True)),
                ("images", models.ImageField(upload_to="media")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cpanel.book",
                        verbose_name="book",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="bookdetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booktype", models.CharField(default=None, max_length=150)),
                ("price", models.DecimalField(decimal_places=2, max_digits=9)),
                ("description", models.TextField(blank=True, default=None, null=True)),
                ("details", models.TextField(blank=True, default="None", null=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cpanel.book",
                        verbose_name="book",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cpanel.product",
                verbose_name="product",
            ),
        ),
        migrations.CreateModel(
            name="Authors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(default=None, max_length=300)),
                (
                    "nofp",
                    models.IntegerField(
                        default=None, verbose_name="number of books published"
                    ),
                ),
                ("description", models.TextField(default=None)),
                (
                    "thumbnail",
                    models.ImageField(
                        default="author_defualt_thumbnail.webp",
                        upload_to="author/thumbnail",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, default="None", null=True, upload_to="author/img"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "books",
                    models.ManyToManyField(
                        blank=True,
                        default=None,
                        to="cpanel.book",
                        verbose_name="author book",
                    ),
                ),
            ],
        ),
    ]
