# Generated by Django 4.1.3 on 2023-02-02 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cpanel", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="on_sale",
        ),
        migrations.RemoveField(
            model_name="book",
            name="sales_discount",
        ),
    ]
