# Generated by Django 4.1.3 on 2023-01-20 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cpanel", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ratings",
            name="comments",
        ),
        migrations.RemoveField(
            model_name="ratings",
            name="title",
        ),
    ]
