# Generated by Django 4.1.3 on 2022-12-10 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cpanel", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="addresse",
            name="phonenumber",
        ),
    ]
