# Generated by Django 4.1.3 on 2023-02-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpanel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="description",
            field=models.TextField(default=None),
        ),
    ]
