# Generated by Django 4.1.3 on 2022-11-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpanel", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="deault_booktype",
            new_name="default_type",
        ),
        migrations.AddField(
            model_name="book",
            name="slug",
            field=models.SlugField(default=None),
        ),
    ]
