# Generated by Django 4.1.3 on 2023-01-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpanel", "0002_remove_ratings_comments_remove_ratings_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="ratings",
            name="comments",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="ratings",
            name="title",
            field=models.TextField(default=None),
        ),
    ]
