# Generated by Django 4.1.3 on 2022-12-03 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpanel", "0002_rename_deault_booktype_book_default_type_book_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="general_settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_title", models.CharField(default=None, max_length=250)),
                (
                    "tage_line",
                    models.CharField(
                        default=None,
                        help_text="In few words, explain what this site is about. ",
                        max_length=250,
                    ),
                ),
                (
                    "default_email",
                    models.EmailField(
                        default=None,
                        help_text="The defaul email on home page.",
                        max_length=254,
                    ),
                ),
                (
                    "defualt_phone",
                    models.CharField(
                        default=None,
                        help_text="The default number on home page.",
                        max_length=150,
                    ),
                ),
                (
                    "facebook_handle",
                    models.CharField(
                        default=None,
                        help_text="Enter your facebook handle.",
                        max_length=150,
                    ),
                ),
                (
                    "twitter_handle",
                    models.CharField(
                        default=None,
                        help_text="Enter your twitter handle.",
                        max_length=150,
                    ),
                ),
                (
                    "instagram_handle",
                    models.CharField(
                        default=None,
                        help_text="Enter your intagram handle.",
                        max_length=150,
                    ),
                ),
                (
                    "youtube_handle",
                    models.CharField(
                        default=None,
                        help_text="Enter your youtube handle.",
                        max_length=150,
                    ),
                ),
                (
                    "pinterest_handle",
                    models.CharField(
                        default=None,
                        help_text="Enter your pinterest handle.",
                        max_length=150,
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        default=None,
                        help_text="bookshop physical address",
                        max_length=150,
                    ),
                ),
            ],
        ),
    ]
