# Generated by Django 4.1.3 on 2023-02-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpanel", "0002_remove_book_on_sale_remove_book_sales_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="category",
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AddField(
            model_name="book",
            name="on_sale",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="book",
            name="on_sale_deadline",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="sales_discount",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
