# Generated by Django 4.1.3 on 2022-12-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpanel", "0003_order_order_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="addresse",
            name="user_type",
            field=models.CharField(default="guest", max_length=30),
        ),
        migrations.AlterField(
            model_name="addresse",
            name="user",
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
