# Generated by Django 4.1.3 on 2022-12-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpanel", "0003_addresse_phonenumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addresse",
            name="phonenumber",
            field=models.CharField(blank=True, default=None, max_length=12, null=True),
        ),
    ]
