# Generated by Django 4.1.3 on 2023-02-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpanel", "0003_book_category_book_on_sale_book_on_sale_deadline_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="slug",
            field=models.SlugField(default=None, unique=True),
        ),
    ]
