# Generated by Django 4.1.3 on 2023-02-07 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpanel", "0003_alter_dealofweek_book_alter_dealofweek_discount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dealofweek",
            name="created_by",
            field=models.EmailField(
                default=None, max_length=254, verbose_name="created by"
            ),
        ),
    ]
