# Generated by Django 4.1.3 on 2023-02-07 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cpanel", "0004_alter_dealofweek_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dealofweek",
            name="created_by",
        ),
    ]
