# Generated by Django 4.1.3 on 2022-12-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpanel", "0004_addresse_user_type_alter_addresse_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="orderid",
            field=models.CharField(default="None", max_length=10),
        ),
    ]
