# Generated by Django 4.1.3 on 2022-12-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpanel", "0004_rename_defualt_phone_general_settings_default_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="general_settings",
            name="address",
            field=models.TextField(default=None, help_text="bookshop physical address"),
        ),
    ]
