# Generated by Django 4.1.3 on 2023-01-26 21:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("cpanel", "0005_onsale"),
    ]

    operations = [
        migrations.CreateModel(
            name="DealofWeek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discount", models.IntegerField(default=0)),
                ("periode", models.DateTimeField(default=None)),
                ("quantity", models.IntegerField(default=0)),
                ("sold", models.IntegerField(default=0)),
                ("created_by", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cpanel.book",
                        verbose_name="deals of the week",
                    ),
                ),
            ],
        ),
    ]
