# Generated by Django 4.1.3 on 2023-01-06 09:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("cpanel", "0005_alter_order_orderid"),
    ]

    operations = [
        migrations.CreateModel(
            name="order_book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.CharField(default=None, max_length=150)),
                ("booktitle", models.CharField(default=None, max_length=250)),
                ("bookquantity", models.IntegerField(default=None)),
                ("bookthumbnail", models.CharField(default=None, max_length=250)),
                ("bookprice", models.DecimalField(decimal_places=2, max_digits=9)),
                ("booktype", models.CharField(default=None, max_length=250)),
                ("bookauthor", models.CharField(default=None, max_length=250)),
                (
                    "bookslug",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "ordernumber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cpanel.order",
                        verbose_name="cart",
                    ),
                ),
            ],
        ),
    ]
