# Generated by Django 4.1.3 on 2022-12-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpanel", "0006_coupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="percentage",
            field=models.CharField(
                default=None, help_text="percentage ex: 20", max_length=100
            ),
        ),
    ]
