# Generated by Django 4.1.3 on 2023-01-06 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cpanel", "0006_order_book"),
    ]

    operations = [
        migrations.DeleteModel(
            name="order_book",
        ),
    ]
