# Generated by Django 4.1.3 on 2023-02-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpanel", "0006_remove_onsale_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onsale",
            name="discount",
            field=models.IntegerField(default=None, verbose_name="discount (%)"),
        ),
    ]
