# Generated by Django 4.1.3 on 2022-12-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpanel", "0007_coupon_percentage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="expires_on",
            field=models.DateTimeField(default=None),
        ),
    ]
