# Generated by Django 4.1.3 on 2023-02-07 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cpanel", "0007_alter_onsale_discount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="on_sale",
        ),
        migrations.RemoveField(
            model_name="book",
            name="on_sale_deadline",
        ),
        migrations.RemoveField(
            model_name="book",
            name="sales_discount",
        ),
    ]
