# Generated by Django 4.1.3 on 2023-01-28 15:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("cpanel", "0007_dealofweek_created_at_alter_dealofweek_created_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="Authors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(default=None, max_length=300)),
                (
                    "nofp",
                    models.IntegerField(
                        default=None, verbose_name="number of books published"
                    ),
                ),
                ("description", models.TextField(default=None)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
