# Generated by Django 4.1.3 on 2023-04-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpanel", "0008_remove_book_on_sale_remove_book_on_sale_deadline_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onsale",
            name="periode",
            field=models.DateField(default=None),
        ),
    ]
