# Generated by Django 4.1.3 on 2022-12-19 08:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("cpanel", "0008_alter_coupon_expires_on"),
    ]

    operations = [
        migrations.CreateModel(
            name="order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "orderid",
                    models.UUIDField(
                        editable=False, unique=True, verbose_name=uuid.uuid4
                    ),
                ),
                ("email", models.EmailField(default=None, max_length=254)),
                ("status", models.CharField(default="pending", max_length=250)),
                ("items", models.CharField(default=None, max_length=300)),
                ("payment_method", models.CharField(default=None, max_length=250)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cpanel.addresse",
                        verbose_name="shipping address",
                    ),
                ),
            ],
        ),
    ]
