# Generated by Django 4.1.3 on 2023-01-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpanel", "0008_authors"),
    ]

    operations = [
        migrations.AddField(
            model_name="authors",
            name="image",
            field=models.ImageField(
                blank=True, default="None", null=True, upload_to="author/img"
            ),
        ),
        migrations.AddField(
            model_name="authors",
            name="thumbnail",
            field=models.ImageField(
                default="author_defualt_thumbnail.webp", upload_to="author/thumbnail"
            ),
        ),
    ]
