# Generated by Django 4.1.3 on 2023-01-06 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cpanel", "0008_order_coupon_order_totol_paid_order_book"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="items",
        ),
    ]
