# Generated by Django 4.1.3 on 2023-01-06 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cpanel", "0009_remove_order_items"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="totol_paid",
            new_name="amount",
        ),
    ]
