# Generated by Django 4.1.3 on 2023-04-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpanel", "0009_alter_onsale_periode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onsale",
            name="periode",
            field=models.DateTimeField(default=None),
        ),
    ]
