# Generated by Django 4.1.3 on 2023-01-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpanel", "0009_authors_image_authors_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="authors",
            name="books",
            field=models.ManyToManyField(
                blank=True, default=None, to="cpanel.book", verbose_name="author book"
            ),
        ),
    ]
