# Generated by Django 4.1.3 on 2023-04-25 12:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("cpanel", "0010_alter_onsale_periode"),
    ]

    operations = [
        migrations.CreateModel(
            name="transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(default=None, max_length=100)),
                ("data", models.TextField(default=None)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cpanel.order",
                        verbose_name="order transaction status",
                    ),
                ),
            ],
        ),
    ]
