# Generated by Django 4.1.3 on 2023-01-06 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cpanel", "0010_rename_totol_paid_order_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cpanel.coupon",
                verbose_name="coupon code",
            ),
        ),
    ]
