# Generated by Django 4.1.3 on 2023-01-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpanel", "0013_alter_order_coupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="discount",
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_fee",
            field=models.CharField(default=None, max_length=250),
        ),
    ]
