# Generated by Django 4.1.3 on 2023-01-06 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cpanel", "0014_order_discount_order_shipping_fee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="discount",
        ),
        migrations.RemoveField(
            model_name="order",
            name="shipping_fee",
        ),
    ]
