# Generated by Django 4.1.3 on 2023-01-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpanel", "0015_remove_order_discount_remove_order_shipping_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="discount",
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_fee",
            field=models.CharField(default=None, max_length=250),
        ),
    ]
